"""Slice 21 IriAI context-layer package."""

from .models import (
    CONTEXT_LAYER_SCHEMA_VERSION,
    CodeSpanRef,
    ContextCompleteness,
    ContextEvidenceSnapshot,
    ContextLayerBudget,
    ContextLayerPackage,
    ContextLayerRequest,
    ContextPackageKind,
    ContextPageContent,
    ContextProviderName,
    IriAILineageRecord,
    ProviderAvailability,
    ProviderIndexResult,
    ProviderLineageRecord,
    ProviderStateRef,
    ProviderStatus,
    compute_context_package_digest,
    compute_iriai_lineage_digest,
    compute_provider_record_digest,
    compute_provider_state_digest,
    context_package_review_ref,
)
from .providers import NativeGitProvider, ProvenanceProvider
from .service import (
    ContextLayerService,
    ContextPageStore,
    IriAILineagePlugin,
    IriAILineageSourceRecord,
)

__all__ = [
    "CONTEXT_LAYER_SCHEMA_VERSION",
    "CodeSpanRef",
    "ContextCompleteness",
    "ContextEvidenceSnapshot",
    "ContextLayerBudget",
    "ContextLayerPackage",
    "ContextLayerRequest",
    "ContextLayerService",
    "ContextPackageKind",
    "ContextPageContent",
    "ContextPageStore",
    "ContextProviderName",
    "IriAILineagePlugin",
    "IriAILineageRecord",
    "IriAILineageSourceRecord",
    "NativeGitProvider",
    "ProviderAvailability",
    "ProviderIndexResult",
    "ProviderLineageRecord",
    "ProviderStateRef",
    "ProviderStatus",
    "ProvenanceProvider",
    "compute_context_package_digest",
    "compute_iriai_lineage_digest",
    "compute_provider_record_digest",
    "compute_provider_state_digest",
    "context_package_review_ref",
]
