from __future__ import annotations

from ._compose_compat import ensure_iriai_compose_compatibility, prefer_canonical_iriai_compose

prefer_canonical_iriai_compose(__file__)
ensure_iriai_compose_compatibility(__file__)
